<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndicatorSeeder extends Seeder
{
    /**
     * * Run the database seeds.
     * */
    public function run(): void
    {
        $indicators = collect([
            (object) ["instrument" => 1, "code" => "1", "desc" => "Rencana pembelajaran guru belum menggambarkan proses pembelajaran yang efektif serta belum berbasis keunggulan Madrasah", "reference" => "Guru perlu memenuhi kompetensi dalam menyusun perencanaan pembelajaran yang menggambarkan implementasi proses pembelajaran yang efektif dan berbasis keunggulan madrasah"],
            (object) ["instrument" => 1, "code" => "2", "desc" => "Rencana pembelajaran guru belum menggambarkan proses pembelajaran yang efektif namun telah berbasis keunggulan Madrasah", "reference" => "Guru perlu memenuhi kompetensi dalam menyusun perencanaan pembelajaran yang menggambarkan implementasi proses pembelajaran yang efektif "],
            (object) ["instrument" => 1, "code" => "3", "desc" => "Rencana pembelajaran guru sebagian mengindikasikan proses pembelajaran dilakukan secara efektif namun belum berbasis keunggulan Madrasah", "reference" => "Guru perlu meningkatkan kompetensi dalam menyusun perencanaan pembelajaran yang menggambarkan implementasi proses pembelajaran yang efektif dan berbasis keunggulan madrasah"],
            (object) ["instrument" => 1, "code" => "4", "desc" => "Rencana pembelajaran guru sebagian mengindikasikan proses pembelajaran dilakukan secara efektif namun telah berbasis keunggulan Madrasah", "reference" => "Guru perlu meningkatkan kompetensi dalam menyusun perencanaan pembelajaran yang menggambarkan implementasi proses pembelajaran yang efektif "],
            (object) ["instrument" => 1, "code" => "5", "desc" => "Rencana pembelajaran guru telah menggambarkan proses pembelajaran yang efektif namun belum berbasis keunggulan Madrasah", "reference" => "Guru perlu melakukan penguatan kompetensi dalam menyusun perencanaan pembelajaran yang menggambarkan implementasi proses pembelajaran yang efektif dan meningkatkan pola pembelajaran berbasis keunggulan madrasah"],
            (object) ["instrument" => 1, "code" => "6", "desc" => "Rencana pembelajaran guru telah menggambarkan proses pembelajaran yang efektif dengan memperhatikan basis keunggulan Madrasah", "reference" => "Guru perlu melakukan penguatan kompetensi dalam menyusun perencanaan pembelajaran yang menggambarkan implementasi proses pembelajaran yang efektif berbasis keunggulan madrasah serta berbagi pemahaman dalam forum komunitas guru"],
            (object) ["instrument" => 2, "code" => "1", "desc" => "Rencana pembelajaran yang disusun oleh guru belum mendukung terlaksananya pembelajaran kontekstual, kebermaknaan, humanis, metakognitif, moderat dan tercapainya misi madrasah", "reference" => "Guru Perlu kegiatan yang mendukung pemahaman guru dalam merencanakan pembelajaran kontekstual, kebermaknaan, humanis, metakognitif, moderat dan tercapainya misi madrasah"],
            (object) ["instrument" => 2, "code" => "2", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mencerminkan pembelajaran kontekstual, bermakna, humanis, metakognitif serta moderat", "reference" => "Guru Perlu kegiatan yang mendukung pemahaman guru dalam merencanakan pembelajaran kontekstual, kebermaknaan, humanis, metakognitif, moderat dan tercapainya misi madrasah secara memadai"],
            (object) ["instrument" => 2, "code" => "3", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mencerminkan pembelajaran kontekstual, bermakna, humanis", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran serta menguatkan pemahamannya dalam konsep pembelajaran kontektual, bermakna, humanis, metakognitif dan moderat"],
            (object) ["instrument" => 2, "code" => "4", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pembelajaran kontekstual, bermakna, humanis, metakognitif ", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran serta dengan upaya memahami konsep pembelajaran kontektual, bermakna, humanis, metakognitif dan moderat"],
            (object) ["instrument" => 2, "code" => "5", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pembelajaran kontekstual, bermakna, humanis, metakognitif serta moderat", "reference" => "Guru Perlu melakukan penguatan kompetensi dalam merencanakan pembelajaran serta meningkatkan implementasi pembelajaran kontektual, bermakna, humanis, metakognitif dan moderat"],
            (object) ["instrument" => 2, "code" => "6", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pembelajaran kontekstual, bermakna, humanis, metakognitif serta moderat dan tercapainya misi madrasah", "reference" => "Guru Perlu melakukan penguatan kompetensi dalam merencanakan pembelajaran serta memberikan dukungan implementasi pembelajaran kontektual, bermakna, humanis, metakognitif dan moderat terhadap teman sejawat dalam forum komunitas guru"],
            (object) ["instrument" => 3, "code" => "1", "desc" => "Rencana pembelajaran yang disusun oleh guru belum mendukung terlaksananya pembelajaran abad 21 serta belum mendukung pengembangan pendidikan karakter dan akhlaqul Karimah ", "reference" => "Guru Perlu memahami konsep dan motivasi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mengembangkan pendidikan karakter dan akhlakul Karimah "],
            (object) ["instrument" => 3, "code" => "2", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian mendukung terlaksananya pembelajaran abad 21 dengan indikasi aktifitas pengembangan pendidikan karakter dan Akhlaqul Karimah", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mengembangkan pendidikan karakter dan akhlakul Karimah "],
            (object) ["instrument" => 3, "code" => "3", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pembelajaran abad 21 dengan indikasi aktifitas pengembangan pendidikan karakter dan Akhlaqul Karimah", "reference" => "Guru Perlu melaksanakan penguatan dan berkontribusi dalam forum komunitas guru untuk program peningkatan merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mengembangkan pendidikan karakter dan akhlakul Karimah "],
            (object) ["instrument" => 4, "code" => "1", "desc" => "Rencana pembelajaran yang disusun oleh guru belum mendukung terlaksananya pembelajaran abad 21 serta belum mengembangkan Budaya Literasi, numerasi, sains dan sosial budaya", "reference" => "Guru Perlu memahami konsep dan motivasi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan Literasi, numerasi, sains dan sosial budaya"],
            (object) ["instrument" => 4, "code" => "2", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan Budaya Literasi", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran Budaya Literasi serta memahami konsep numerasi, sains dan sosial budaya"],
            (object) ["instrument" => 4, "code" => "3", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan Budaya numerasi", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran Budaya Numerasi serta memahami konsep literasi, sains dan sosial budaya"],
            (object) ["instrument" => 4, "code" => "4", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan Budaya sains", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran sains serta memahami konsep literasi, numerasi dan sosial budaya"],
            (object) ["instrument" => 4, "code" => "5", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan Budaya literasi, numerasi, sains dan sosial budaya serta sains secara konsisten", "reference" => "Guru Perlu melaksanakan penguatan dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran Budaya literasi, numerasi, sains dan sosial budaya secara harmonis"],
            (object) ["instrument" => 5, "code" => "1", "desc" => "Rencana pembelajaran yang disusun oleh guru belum mendukung terlaksananya pembelajaran abad 21 serta tidak mengembangkan Berfikir Kritis, kolaboratif, komunikatif dan kreatif", "reference" => "Guru Perlu memahami konsep dan motivasi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pengembangan Berfikir Kritis, kolaboratif, komunikatif dan kreatif"],
            (object) ["instrument" => 5, "code" => "2", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan Berfikir Kritis", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran pengembangan Berfikir Kritis serta memahami konsep kolaboratif, komunikatif dan kreatif"],
            (object) ["instrument" => 5, "code" => "3", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan Budaya kolaboratif dan komunikatif", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran kolaboratif dan komunikatif serta memahami konsep literasi, sains dan sosial budaya"],
            (object) ["instrument" => 5, "code" => "4", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan berfikir kreatif", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran sains serta memahami konsep Berfikir Kritis dan kreatif"],
            (object) ["instrument" => 5, "code" => "5", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pembelajaran abad 21 dengan mengembangkan Berfikir Kritis, kolaboratif, komunikatif dan kreatif secara konsisten ", "reference" => "Guru Perlu melaksanakan penguatan dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pengembangan Berfikir Kritis, kolaboratif, komunikatif dan kreatif"],
            (object) ["instrument" => 6, "code" => "1", "desc" => "Rencana pembelajaran yang disusun oleh guru belum mendukung terlaksananya pembelajaran abad 21 serta belum mengindikasikan pengembangan kemampuan pemecahan masalah ", "reference" => "Guru Perlu memahami konsep dan motivasi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mengembangkan kemampuan dalam memecahkan masalah "],
            (object) ["instrument" => 6, "code" => "2", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian mendukung terlaksananya pembelajaran abad 21 serta telah mengindikasikan pengembangan kemampuan pemecahan masalah ", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mengembangkan kemampuan dalam memecahkan masalah "],
            (object) ["instrument" => 6, "code" => "3", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pembelajaran abad 21 serta mengindikasikan pengembangan kemampuan pemecahan masalah secara konsisten ", "reference" => "Guru Perlu melaksanakan penguatan dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung pengembangan kemampuan dalam memecahkan masalah "],
            (object) ["instrument" => 7, "code" => "1", "desc" => "Rencana pembelajaran yang disusun oleh guru belum mendukung implementasi pendekatan pembelajaran saintifik dengan model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya", "reference" => "Guru Perlu kegiatan yang mendukung pemahaman guru dalam merencanakan pembelajaran yang mendukung mendukung implementasi pendekatan pembelajaran saintifik dengan model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 7, "code" => "2", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Problem solving", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Problem solving serta memahami konsep Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 7, "code" => "3", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran Dicovery Learning", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Dicovery Learning serta memahami konsep Problem solving, Project Base Learning, Inquiry"],
            (object) ["instrument" => 7, "code" => "4", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran Project Base Learning", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Project Base Learning serta memahami konsep Dicovery Learning, Problem solving, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 7, "code" => "5", "desc" => "Rencana pembelajaran yang disusun oleh guru sebagian telah mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran inquiri", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran inquiri serta memahami konsep Dicovery Learning, Project Base Learning, Problem solving"],
            (object) ["instrument" => 7, "code" => "6", "desc" => "Rencana pembelajaran yang disusun oleh guru telah mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya secara konsisten", "reference" => "Guru Perlu melaksanakan penguatan dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran saintifik dengan model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 8, "code" => "1", "desc" => "Perencanaan pembelajaran yang disusun oleh guru belum mendukung pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar", "reference" => "Guru Perlu memahami konsep dan motivasi dalam merencanakan pembelajaran yang mendukung pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar"],
            (object) ["instrument" => 8, "code" => "2", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah berbasis pemanfaatan teknologi informasi ", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung pemanfaatan teknologi informasi serta memahami pentingnya pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar"],
            (object) ["instrument" => 8, "code" => "3", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah berbasis pemanfaatan sumber daya yang terdapat disekitar lingkungan ", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar serta memahami pentingnya pemanfaatan teknologi informasi "],
            (object) ["instrument" => 8, "code" => "4", "desc" => "Perencanaan pembelajaran yang disusun oleh guru sebagian berbasis pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mendukung pemanfaatan teknologi informasi serta pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar"],
            (object) ["instrument" => 8, "code" => "5", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah didukung pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar secara konsisten", "reference" => "Guru Perlu melaksanakan penguatan dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumber daya yang terdapat dilingkungan sekitar"],
            (object) ["instrument" => 9, "code" => "1", "desc" => "Perencanaan pembelajaran yang disusun oleh guru belum mengintegrasikan penilaian proses pembelajaran dan hasil belajar secara memadai", "reference" => "Guru Perlu kegiatan yang mendukung pemahaman guru dalam merencanakan pembelajaran yang mengintegrasikan penilaian proses pembelajaran dan hasil belajar secara memadai"],
            (object) ["instrument" => 9, "code" => "2", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah mengintegrasikan penilaian proses yang belum sepenuhnya mencakup seluruh ranah penilaian pembelajaran", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mengintegrasikan penilaian proses pembelajaran yang mencakup seluruh ranah penilaian dan upaya memahami konsep penilaian hasil belajar secara memadai"],
            (object) ["instrument" => 9, "code" => "3", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah mengintegrasikan penilaian proses mencakup seluruh ranah penilaian pembelajaran secara konsisten", "reference" => "Guru Perlu meningkatkan kompetensi dalam merencanakan pembelajaran yang mengintegrasikan penilaian hasil pembelajaran yang mencakup seluruh ranah penilaian dan upaya memahami konsep penilaian proses pembelajaran secara memadai"],
            (object) ["instrument" => 9, "code" => "4", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah mengintegrasikan penilaian hasil pembelajaran", "reference" => "Guru Perlu meningkatkan penguatan kompetensi dalam merencanakan pembelajaran yang mendukung penilaian yang mengintegrasikan penilaian proses pembelajaran dan hasil belajar secara memadai"],
            (object) ["instrument" => 9, "code" => "5", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah mengintegrasikan penilaian hasil pembelajaran dilengkapi dengan lampiran rencana penilaian pembelajaran secara terpadu", "reference" => "Guru Perlu meningkatkan penguatan kompetensi dalam merencanakan pembelajaran yang mendukung penilaian yang mengintegrasikan penilaian proses pembelajaran dan hasil belajar beserta lampiran rencana penilaian secara terpadu "],
            (object) ["instrument" => 9, "code" => "6", "desc" => "Perencanaan pembelajaran yang disusun oleh guru telah mengintegrasikan penilaian proses pembelajaran dan penilaian hasil pembelajaran dilengkapi dengan lampiran rencana penilaian pembelajaran secara terpadu", "reference" => "Guru Perlu melaksanakan penguatan dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung penilaian yang mengintegrasikan penilaian proses pembelajaran dan hasil belajar beserta lampiran rencana penilaian secara terpadu "],
            (object) ["instrument" => 10, "code" => "1", "desc" => "Proses pembelajaran belum tersaji secara kontekstual, kebermaknaan, humanis, metakognitif dan moderat, Pembelajaran didominasi penyampaian komunikasi satu arah dari guru", "reference" => "Guru Perlu memperluas wawasan pemahaman yang mendorong tumbuhnya semangat perubahan mindset dalam wujud pembelajaran kontekstual, bermakna, memperhatikan potensi humanistik, serta metakognitif dan moderat"],
            (object) ["instrument" => 10, "code" => "2", "desc" => "Proses pembelajaran sebagian sudah memenuhi syarat dari kriteria pembelajaran kontekstual, bermakna, humanis, metakognitif, dan moderat. Kegiatan pembelajaran terlaksana secara antusias", "reference" => " Guru hendaknya meningkatkan antusiasme mendampingi dan membimbing pembelajaran secara kontekstual, memberikan pengalaman bermakna, mendorong ide, gagasan dan materi untuk membentuk konsep baru"],
            (object) ["instrument" => 10, "code" => "3", "desc" => "Pelaksanaan pembelajaran tersaji dengan antusiasme yang tinggi, dilakukan secara kontekstual, memberikan pengalaman bermakna, menghargai potensi humanistik.", "reference" => "Guru Perlu meningkatkan kompetensi sebagai dukungan dari aktivitas pembelajaran yang antusias memperhatikan potensi peserta didik, memberikan pengalaman bermakna, mendukung proses pembelajaran kontekstual"],
            (object) ["instrument" => 10, "code" => "4", "desc" => "Pelaksanaan pembelajaran telah mencerminkan pendayagunaan potensi humanistik, memperhatikan proses pembelajaran bermakna, kontekstual, menggabungkan berbagai ide gagasan baru secara harmonis", "reference" => "Guru Perlu menguatkan kompetensi diri dengan secara terus menerus dan systematise melaksanakan proses pembelajaran n kontektual, bermakna, humanis, metakognitif dan moderat secara konsisten "],
            (object) ["instrument" => 11, "code" => "1", "desc" => "Kegiatan pembelajaran masih dilaksanakan secara tradisional, berpusat pada guru dengan pesan pesan karakter dan akhlakul Karimah secara lisan, belum mengindikasikan pembelajaran yang mencerminkan kecakapan abad 21", "reference" => "Guru Perlu berupaya merubah mindset dalam melaksanakan kegiatan pembelajaran agar sesuai dengan semangat perubahan dan kebutuhan kecakapan abad 21, dengan tidak lupa menanamkan penguatan pendidikan karakter dan akhlakul karimah secara terpadu"],
            (object) ["instrument" => 11, "code" => "2", "desc" => "Pelaksanaan pembelajaran sebagian telah mengadaptasikan beberapa metode yang memungkinkan peserta didik turut aktif, dengan penerapan penguatan karakter dan akhlakul Karimah yang belum sepenuhnya menjiwai proses kegiatan pembelajaran", "reference" => "Guru Perlu meningkatkan kompetensi dan membiasakan pemanfaatan pendekatan pembelajaran yang memicu tumbuhnya kecakapan abad 21 berupa sikap kritis kratif kolaboratif dan komunikatif didukung dengan pembiasaan penguatan karakter dan akhlakul karimah "],
            (object) ["instrument" => 11, "code" => "3", "desc" => "Pembelajaran terlaksana secara antusias, memberikan pengalaman yang mengindikasikan kecakapan abad 21 berupa aktifitas komunikasi, kolaborasi serta upaya memunculkan sikap kritis dan kreatif dijiwai dengan penerapan karakter dan akhlakul Karimah secara terpadu", "reference" => "Guru Perlu mendororong dan berkontribusi bagi upaya peningkatan kompetensi dalam forum komunitas guru guna mendukung implementasi pembelajaran yang memacu kecakapan abad 21 dan dijiwai penerapan penguatan karakter dan akhlak mulia"],
            (object) ["instrument" => 12, "code" => "1", "desc" => "Kegiatan pembelajaran belum mengintegrasikan kecakapan abad 21 yang ditandai belum dilakukannya pembiasaan budaya literasi, numerasi, sains dan sosial budaya", "reference" => "Guru perlu meningkatkan pemahaman dan perubahan orientasi pembelajaran yang menekankan kepada kecakapan abad 21 dengan indikasi pemenuhan penguatan budaya literasi, numerasi, sains dan sosial budaya melalui perubahan mindset secara konsisten"],
            (object) ["instrument" => 12, "code" => "2", "desc" => "Kegiatan pembelajaran telah mendukung sebagian indikasi kecakapan abad 21 dengan fokus pada pengembangan Budaya Literasi namun belum berdampak pada kebiasaan yang dilakukan oleh siswa", "reference" => "Guru perlu meningkatkan implementasi pembelajaran yang berorientasi pada kecakapan abad 21, dengan berfokus pada penguatan budaya literasi yang memunculkan dampak bagi terbentuknya sikap senang membaca pada berbagai kesempatan "],
            (object) ["instrument" => 12, "code" => "3", "desc" => "Kegiatan pembelajaran telah mendukung sebagian indikasi kecakapan abad 21 dengan fokus pada pengembangan Budaya sains yang dilakukan secara terpadu dalam kegiatan intrakurikuler", "reference" => "Guru perlu meningkatkan implementasi pembelajaran yang berorientasi pada kecakapan abad 21, dengan berfokus pada penguatan budaya numerasi yang memberikan dampak kepada pembentukan pembiasaan numerasi"],
            (object) ["instrument" => 12, "code" => "4", "desc" => "Kegiatan pembelajaran telah mendukung sebagian indikasi kecakapan abad 21 dengan fokus pada pengembangan Budaya Numerasi yang dilakukan secara terpadu dalam kegiatan intrakurikuler", "reference" => "Guru perlu meningkatkan implementasi pembelajaran yang berorientasi pada kecakapan abad 21, dengan tidak sekedar berfokus pada penguatan budaya sains serta berdampak pada pembentukan pola pikir saintis "],
            (object) ["instrument" => 12, "code" => "5", "desc" => "Kegiatan pembelajaran telah mendukung terpenuhinya kecakapan abad 21 yang dilakukan secara antusias dan terpadu dan memberi dampak kepada terbentuknya budaya baca dan menghasilkan karya literasi seperti majalah dinding dan karya lainnya", "reference" => "Guru telah memahami dan mengimplementasikan pembelajaran yang mengakomodasi terciptanya budaya literasi, numerasi,sains dan budaya sosial secara konsisten serta memberikan dampak yang positif kepada peserta didik, diharapkan guru dapat pula berbagi dalam komunitas KKG mengembangkan kemampuannya"],
            (object) ["instrument" => 13, "code" => "1", "desc" => "Pembelajaran yang dilakukan oleh guru belum mengindikasikan pemenuhan kecakapan abad 21 yang tercermin dalam proses pembelajaran yang dilakukan guru lebih banyak menjelaskan dan siswa memperhatikan serta mengerjakan tugas yang diberikan ", "reference" => "Guru Perlu memahami konsep dan motivasi dalam proses pembelajaran yang mencerminkan abad 21 serta merubah pola pembelajaran yang hanya terkesan pewarisan pengetahuan kepada peserta didik "],
            (object) ["instrument" => 13, "code" => "2", "desc" => "Pembelajaran belum sepenuhnya mengindikasikan pemenuhan kecakapan abad 21, pengembangan kritikal thinking baru sebatas pemberian kesempatan kepada siswa secara aktif (membaca, bertanya, berdiskusi dan menggunakan media yang tersedia)", "reference" => "Guru Perlu meningkatkan semangat mengimplementasikan pembelajaran yang mendukung terlaksananya kecakapan abad 21 yang yang berfokus pada pengembangan kritikal thinking dan berdampak pada sikap kritis siswa"],
            (object) ["instrument" => 13, "code" => "3", "desc" => "Pembelajaran belum sepenuhnya mengindikasikan pemenuhan kecakapan abad 21, pengembangan suasana kelas yang kolaboratif dan komunikatif telah disajikan melalui pengalaman konkrit menyajikan ide ide yang bermanfaat bagi kehidupan", "reference" => "Guru Perlu meningkatkan semangat dan kompetensi dalam mewujudkan pembelajaran abad 21 yang memunculkan sikap kolaboratif dan komunikatif serta memicu dampak budaya kolaborasi peserta didik"],
            (object) ["instrument" => 13, "code" => "4", "desc" => "Sebagian aspek yang mengindikasikan pelaksanaan pembelajaran yang mengintegrasikan kecakapan abad 21 telah tersajikan secara baik, antusiasme siswa dalam mengemukakan gagasan dalam bentuk kritikal thinking dan pembinaan kreatifitas melalui pengalaman konkret", "reference" => "Guru Perlu meningkatkan kompetensi dalam mewujudkan pembelajaran abad 21 yang secara khusus mencerminkan pembelajaran sains serta berdampak dalam sikap saintis dalam kehidupan sehari hari"],
            (object) ["instrument" => 13, "code" => "5", "desc" => "Proses pembelajaran telah terlaksana sangat baik dengan mengintegrasikan kecakapan abad 21 serta mendukung budaya kreatifitas dan kritikal thinking yang dilakukan secara konsisten dalam bentuk pengalaman konkret, dan bermakna serta memberikan dampak kemampuan siswa dalammemecahkan masalah ", "reference" => "Guru Perlu melaksanakan pengembangan diri dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang secara khusus mencerminkan pengembangan Berfikir Kritis, kolaboratif, komunikatif dan kreatif"],
            (object) ["instrument" => 14, "code" => "1", "desc" => "Guru belum menunjukan proses pembelajaran yang mendukung kecakapan abad 21 yang berdampak kepada terbentuknya kemampuan memecahkan masalah", "reference" => "Guru Perlu memahami konsep dan semangat dalam menerapkan proses pembelajaran kecakapan abad 21 yang diindikasikan dengan pemahaman tentang kemampuan mengidentifikasi, menganalisis dan memecahkan masalah "],
            (object) ["instrument" => 14, "code" => "2", "desc" => "Guru telah menunjukan sebagian upaya untuk membiasakan peserta didik melalui kecakapan abad 21 dserta membina kemampuan memecahkan masalah melalui tugas tugas yang diberikan", "reference" => "Guru Perlu meningkatkan kompetensi proses pembelajaran yang mendukung terlaksananya pembelajaran abad 21 yang berdampak pada kebiasaan siswa dalam mengidentifikasi masalah, menganalisis dan memecahkan masalah "],
            (object) ["instrument" => 14, "code" => "3", "desc" => "Pembelajaran yang dilakukan oleh guru telah mencerminkan kemampuan kecakapan abad 21 yang diindikasikan dengan dibinanya kemampuan mengidentifikasi masalah,menganalisis serta secara kreatif mengambil keputusan ", "reference" => "Guru Perlu mengembangkan kompetensinya dan berkontribusi dalam meningkatkan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung pengembangan kemampuan dalam memecahkan masalah secara kreatif"],
            (object) ["instrument" => 15, "code" => "1", "desc" => "Guru belum mengimplementasikan pendekatan pembelajaran saintifik dalam pembelajaran tematik integratif sehingga belum mendorong terimplementasikannya model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya", "reference" => "Guru Perlu meningkatkan pemahaman dan semangat merubah mindset yang mendukung implementasi pendekatan pembelajaran saintifik dengan model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 15, "code" => "2", "desc" => "Guru telah mulai mencoba melaksanakan pembelajaran menggunakan Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Problem solving", "reference" => "Guru Perlu meningkatkan kompetensi dalam mengimplementasikan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Problem solving serta memahami konsep Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 15, "code" => "3", "desc" => "Guru sebagian telah melaksanakan pembelajaran yang mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran Dicovery Learning", "reference" => "Guru Perlu meningkatkan kompetensi dalam mengimplementasikan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Dicovery Learning serta memahami konsep Problem solving, Project Base Learning, Inquiry"],
            (object) ["instrument" => 15, "code" => "4", "desc" => "Guru sebagian telah melaksanakan pembelajaran yang mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran Project Base Learning", "reference" => "Guru Perlu meningkatkan kompetensi kompetensi dalam mengimplementasikan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran Project Base Learning serta memahami konsep Dicovery Learning, Problem solving, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 15, "code" => "5", "desc" => "Guru sebagian telah melaksanakan pembelajaran yang mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran inquiri", "reference" => "Guru Perlu meningkatkan kompetensi kompetensi dalam mengimplementasikan pembelajaran yang mendukung terlaksananya Pendekatan pembelajaran saintifik dengan mengembangkan pembelajaran inquiri serta memahami konsep Dicovery Learning, Project Base Learning, Problem solving"],
            (object) ["instrument" => 15, "code" => "6", "desc" => "Guru sebagian telah melaksanakan pembelajaran yang mendukung terlaksananya pendekatan pembelajaran saintifik dengan mengembangkan model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya secara konsisten", "reference" => "Guru Perlu mengembangkan , berkontribusi dan berinisiatif dalam menginsiprasi peningkatan kompetensi melalui forum komunitas dalam merencanakan pembelajaran yang mendukung terlaksananya pembelajaran saintifik dengan model pembelajaran Problem solving, Dicovery Learning, Project Base Learning, Inquiry,dan sejenisnya"],
            (object) ["instrument" => 16, "code" => "1", "desc" => "Guru belum melaksanakan pembelajaran yang mendukung pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumberdaya yang terdapat dilingkungan sekitar", "reference" => "Guru Perlu memahami konsep dan motivasi dalam melaksanakan pembelajaran serta mencoba kegiatan pembelajaran yang mengkolaborasikan pemanfaatan sumberdaya yang terdapat dalam linkungan madrasah maupun luar madrasah dengan pemanfaatan teknologi informasi "],
            (object) ["instrument" => 16, "code" => "2", "desc" => "Pelaksanaan pembelajaran yang dilakukan oleh guru telah memanfaatkan teknologi informasi yang dimanfaatkan untuk mencari dan menemukan sumber belajar", "reference" => "Guru Perlu mengkombinasikan pemanfaatan teknologi informasi serta berkreasi memanfaatkan teknologi informasi bukan sekedar sebagai alat guna mencari sumber ajar "],
            (object) ["instrument" => 16, "code" => "3", "desc" => "pelaksanaan pembelajaran yang dilakukan oleh guru telah berbasis teknologi dan informasi yang dilakukan bukan hanya sekedar untuk mencari dan menemukan ide sumber belajar tetapi memanfaatkannya sebagai sarana penyampaian pembelajaran ", "reference" => "Guru Perlu memanfaatkan teknologi informasi disamping sebagai alat untuk mencari sumber informasi juga memberikan pengalaman langsung sebagai alat untuk berkomunikasi dan membentuk kompetensi digital secara berimbang "],
            (object) ["instrument" => 16, "code" => "4", "desc" => "pelaksanaan pembelajaran yang dilakukan oleh guru telah mendukung pemanfaatan sumberdaya berbasis lingkungan baik didalam madrasah maupun diluar madrasah sebagai sumber belajar", "reference" => "Guru Perlu meningkatkan pengalaman langsung berupa pemanfaatan terhadap sumberdaya yang terdapat dilingkungan madrasah maupun luar madrasah sebagai sarana meningkatkan kebermaknaan proses pembelajaran "],
            (object) ["instrument" => 16, "code" => "5", "desc" => "pelaksanaan pembelajaran mencerminkan kegiatan inovatif dan kreatif didukung pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumberdaya yang terdapat dilingkungan sekitar secara konsisten", "reference" => "Guru Perlu mengembangkan kompetensinya dan berkontribusi dalam forum komunitas dalam merencanakan pembelajaran yang mendukung pemanfaatan teknologi informasi dan/ atau pemanfaatan terhadap sumberdaya yang terdapat dilingkungan sekitar"],
            (object) ["instrument" => 17, "code" => "1", "desc" => "penilaian proses dan hasil belajar yang dilakukan oleh guru belum memperhatikan tujuan pembelajaran.", "reference" => "Guru perlu memahami tujuan pembelajaran serta berupaya menyajikan naskah soal berdasarkan tujuan yang telah ditetapkan "],
            (object) ["instrument" => 17, "code" => "2", "desc" => "penilaian proses dan hasil belajar yang dilakukan oleh guru telah sesuai tujuan pembelajaran namun belum digunakan untuk perbaikan pembelajaran.", "reference" => "Guru Perlu melaksanakan analisis hasil penilaian pembelajaran yang harus dijadikan pedoman dalam melakukan kegiatan perbaikan dan pengayaan "],
            (object) ["instrument" => 17, "code" => "3", "desc" => "penilaian proses dan hasil belajar yang dilakukan oleh guru mencakup 3 ranah penilaian ", "reference" => "penilaian proses pembelajaran harus meliputi sikap, pengetahuan dan keterampilan yang harus dilaksanakan untuk mengetahui tingkat keberhasilan dalam kegiatan pembelajaran "],
            (object) ["instrument" => 17, "code" => "4", "desc" => "penilaian proses dan hasil belajar yang dilakukan oleh guru mencakup 3 ranah penilaian dan di dukung dengan teknik penilaian yang sesuai dengan karakteristiknya masing masing ", "reference" => "Guru Perlu meningkatkan pemahaman tentang teknik - teknik yang harus dilakukan dalam masing masing ranah penilaian "],
            (object) ["instrument" => 17, "code" => "5", "desc" => "penilaian proses dan hasil belajar yang dilakukan oleh guru dilakukan secara sistematis melalui tahapan perencanaan pelaksanaan dan mendapatkan hasil penilaian yang memadai", "reference" => "Guru Perlu meningkatkan keterpaduan antara persiapan berupa kisi kisi soal dengan naskah soal serta teknik penilaian yang dilakukan "],
            (object) ["instrument" => 17, "code" => "6", "desc" => "kegiatan penilaian proses dan hasil belajar yang dilakukan oleh guru menggunakan berbagai teknik penilaian untuk mengetahui pencapaian tujuan pembelajaran secara sistemis dan berkesinambungan yang berdampak pada perbaikan proses pembelajaran dan hasil belajar siswa.", "reference" => "Guru Perlu mengembangkan hasil penilaian yang dilakukan agar berdampak terhadap perbaikan pembelajaran, melalui aktifitas analiais hasil penilaian, usaha perbaikan dan pengayaan serta tindak lanjut hasil penilaian pembelajaran "],
            (object) ["instrument" => 18, "code" => "1", "desc" => "Instrumen penilaian yang dibuat oleh guru belum mempertimbangkan kompetensi dan tujuan yang disusun dalam perencanaan pembelajaran ", "reference" => "Guru Perlu mengkaji pengembangan kompetensi dan pemahaman tentang cara mengevaluasi kompetensi siswa yang tercantum dalam standar isi"],
            (object) ["instrument" => 18, "code" => "2", "desc" => "Instrumen penilaian yang disusun oleh guru diambil dari buku, Lembar Kerja siswa dengan asumsi instrumen penilaian sudah menyesuaikan hasil pembelajaran", "reference" => "Guru perlu memahami prosedur penilaian serta diberikan motivasi agar terbiasa menyusun naskah soal secara mandiri "],
            (object) ["instrument" => 18, "code" => "3", "desc" => "Instrumen penilaian yang dimiliki terbatas berupa instrumen penilaian pengetahuan, sedangkan penilaian sikap dan keterampilan tidak disusun", "reference" => "Guru Perlu meningkatkan kompetensi tentang 3 ranah yang dikembangkan dalam pembelajaran serta memahami bagaimana cara melaksanakan penilaiannya "],
            (object) ["instrument" => 18, "code" => "4", "desc" => "Instrumen penilaian yang disusun oleh guru sesuai dengan kompetensi yang dikembangkan dalam ranah pengetahuan, sikap dan keterampilan", "reference" => "Guru Perlu mengimlementasikan kegiatan penilaian pembelajaran yang sesuai dengan kompetensi yang dikembangkan didalam standar isi dalam 3 ranah yakni pengetahuan, sikap dan keterampilan "],
            (object) ["instrument" => 19, "code" => "1", "desc" => "Naskah soal yang disusun belum didasarkan kepada taksonomi yang sedang dikembangkan sihingga naskah soal HOTS belum terpenuhi", "reference" => "Guru Perlu meningkatkan pemahaman dalam taksonomi kompetensi baik pengetahuan sikap maupun keterampilan serta menerapkannya dalam penyusunan naskah soal "],
            (object) ["instrument" => 19, "code" => "2", "desc" => "Naskah soal yang disusun telah memenuhi kriteria penyusunan naskah soal HOTS namun belum mengintegrasikan dengan budaya literasi dan akhlakul karimah yang dikembangkan ", "reference" => "Guru Perlu meningkatkan kemandirian dalam menyajikan instrumen penilaian "],
            (object) ["instrument" => 19, "code" => "3", "desc" => "Naskah soal yang disusun mempertimbangkan level High Order Thinking Skill dan secara sistematis mengintegrasikan budaya literasi dan karakter akhlakul Karimah ", "reference" => "Guru Perlu mengembangkan kemampuan penyusunan naskah soal berbasis High Order thinking Skill dan secara konsisten dijiwai dengan budaya literasidan akhlakul karimah "],
            (object) ["instrument" => 20, "code" => "1", "desc" => "Naskah soal yang disusun oleh guru belum mempertimbangkan sikap menghormati, menghargai perbedaan suku, ras tolerasni, moderasi dan komitmen berbangsa ", "reference" => "Guru perlu meningkatkan pemahaman sikap toleran terhadap berbagai perbedaan demi mewujudkan komitmen berbangsa"],
            (object) ["instrument" => 20, "code" => "2", "desc" => "Naskah soal yang disusun sebagian memperhatikan sikap menghormati, menghargai perbedaan suku, ras tolerasni, moderasi dan komitmen berbangsa ", "reference" => "Guru perlu mengimplementasikan pemahaman sikap toleran terhadap berbagai perbedaan demi mewujudkan komitmen berbangsa"],
            (object) ["instrument" => 20, "code" => "3", "desc" => "Naskah soal yang disusun telah memperhatikan sikap menghormati, menghargai perbedaan suku, ras tolerasni, moderasi dan komitmen berbangsa ", "reference" => "Guru perlu meningkatkan implementasi dan kesadaran sikap toleran terhadap berbagai perbedaan demi mewujudkan komitmen berbangsa"],
            (object) ["instrument" => 20, "code" => "4", "desc" => "Naskah soal yang disusun telah memperhatikan sikap menghormati, menghargai perbedaan suku, ras tolerasni, moderasi dan komitmen berbangsa serta ditelaah oleh tim penyusun naskah untuk menghindarkan kemungkinan pemahaman yang tidak sesuai", "reference" => "Guru perlu meningkatkan implementasi dan kesadaran serta sikap mengevaluasi terhadap muncuknya sikap toleran terhadap berbagai perbedaan demi mewujudkan komitmen berbangsa"],
            (object) ["instrument" => 21, "code" => "1", "desc" => "Penilaian yang dilakukan oleh guru belum memanfaatkan teknologi informasi dan sumber daya yang tersedia di lingkungan ", "reference" => "Guru Perlu memahami perubahan mindset yang sedang berkembang serta memiliki sikap terbuka terhadap perubahan dan perkembangan teknologi dan kesadaran berbasis lingkungan "],
            (object) ["instrument" => 21, "code" => "2", "desc" => "Penilaian yang dilakukan oleh guru sebagian memanfaatkan teknologi informasi sebagai media", "reference" => "Guru Perlu mengimplementasikan pola penilaian sesuai dengan karakter penilaian dengan mempertimbanglan penggunaan teknologi informasi atau pembedayaan lingkungan sekitar "],
            (object) ["instrument" => 21, "code" => "3", "desc" => "Penilaian yang dilakukan oleh guru sebagian memenfaatkan sumber daya dan lingkungan yang tersedia di sekitar madrasah ", "reference" => "Guru Perlu mengimplementasikan pola penilaian sesuai dengan sumber daya yang dimilki guna mempertegas pembelajaran kontekstual dan kebermaknaan "],
            (object) ["instrument" => 21, "code" => "4", "desc" => "Penilaian yang dilakukan oleh guru memadukan pemanfaatan teknologi informasi dan sumberdaya yang tersedia dilingkungan sekitar ", "reference" => "Guru Perlu secara bijak mempertimbangkan efektifitas pemanfaatan teknologi informasi dan sumberdaya lingkungan sesuai kebutuhan dalam kegiatan penilaian "],
            (object) ["instrument" => 21, "code" => "5", "desc" => "Penilaian yang dilakukan oleh guru memadukan pemanfaatan teknologi informasi dan sumberdaya yang tersedia dilingkungan sekitar secara konsisten dan diolah menggunakan teknologi", "reference" => "Guru Perlu secara konsisten dan efektif memanfaatkan teknologi informasi sebagai sarana penilaian dan pengolahan hasil penilaian serta memberdayakan secara maksimal sumberdaya yang dimiliki"],
            (object) ["instrument" => 22, "code" => "1", "desc" => "Guru belum melaksanakan analisis terhadap kegiatan penilaian yang dilakukannya ", "reference" => "Guru Perlu memahami konsep dan semangat perbaikan mutu pembelajaran melalui kegiatan analisis terhadap hasil penilaian "],
            (object) ["instrument" => 22, "code" => "2", "desc" => "Guru telah melaksanakan analisis hasil penilaian namun belum menjadi pertimbangan bagi upaya perbaikan proses pembelajaran ", "reference" => "Guru Perlu melakukan analisis secara sistematis dan menjadikannya sebagai pijakan untuk melakukan perbaikan dan pengayaan "],
            (object) ["instrument" => 22, "code" => "3", "desc" => "Guru melaksanakan analisis penilaian secara konsisten serta menjadikannya sebagai pijakan guna melaksanakan perbaikan dan pengayaan ", "reference" => "Guru perlu berkomitmen dan saling berbagi dalam meningkatkan kualitas penilaian melalui aktifitas analisis penilaian hasil belajar "],
            (object) ["instrument" => 23, "code" => "1", "desc" => "Guru belum mempertimbangkan hasil penilaian dan analisis dalam program tindak lanjut ", "reference" => "Guru Perlu meningkatkan pemahaman dan semangat memperbaiki pembelajaran melalui tindak lanjut hasil penilaian "],
            (object) ["instrument" => 23, "code" => "2", "desc" => "Guru telah memiliki program tindak lanjut hasil penilaian namun belum sepenuhnya merupakan hasil analisis terhadap penilaian pembelajaran ", "reference" => "Guru Perlu meningkatkan kesadaran analitis untuk melakukan tindak lanjut berdasarkan hasil analisis penilaian pembelajaran "],
            (object) ["instrument" => 23, "code" => "3", "desc" => "Guru telah memiliki program tindak lanjut hasil penilaian yang dilakukan berdasarkan analisis terhadap pencapaian hasil pembelajaran ", "reference" => "Guru Perlu meningkatkan komitmen melaksanakan tindak lanjut melalui hasil analisis serta memberikan pengalaman positif bagi upaya peningkatan kualitas pembelajaran "],
            (object) ["instrument" => 23, "code" => "4", "desc" => "Guru telah memiliki program tindak lanjut hasil penilaian yang dilakukan berdasarkan analisis terhadap pencapaian hasil pembelajaran serta berimbas pada peningkatan kompetensi siswa ", "reference" => "Guru Perlu melaksanakan analisis secara kreatif dan menjadikannya pijakan untuk meningkatkan kualitas dan memberikan dampak yang positif bagi kualitas pembelajaran "],

        ]);

        $indicators->map(function ($indicator) {
            DB::table('indicators')->insert([
                'instrument' => $indicator->instrument,
                'code' => $indicator->code,
                'desc' => $indicator->desc,
                'reference' => $indicator->reference
            ]);
        });
    }
}
